### ISSUE TITLE
Cannot Login with provided URL and Credentials

### ISSUE THREAD

**Issue by Jonnehs** [hultenvp/solis-sensor#294]
**Describe the bug**
Unable to login, but the test script does connect to the API and work

**Versions**
HASS Version 2023.06.1
HACS version 1.32.1
Integration version 3.3.3

**Debug logs**
couldnt see any generated, except the error that the integration has no plants configured (duh)

**Screenshots**
![image](https://github.com/hultenvp/solis-sensor/assets/11739441/4da81f95-e7d2-4314-954b-6bbdb5af6e61)
![image](https://github.com/hultenvp/solis-sensor/assets/11739441/ac51af86-b45b-404d-89d4-9c6f4a3324e5)

**Comment by advertisingfree** [comment]
This integration is not working at all. I have been wasting so much time.

**Comment by Luke-Beck** [comment]
Just commenting to say I'm getting the same issue.
I've recently migrated to SolisCloud from the old platform, if that's a common denominator.

**Comment by FGOD1983** [comment]
also migrated from the old platform to soliscloud and having the same issue. Then again, I'm also having issues getting the verification mail from Soliscloud which only worked once and thank god I made a picture of the key and secret so I at least am able to try login later on...

But yeah, it seems that something changed on the api and made it work in a different way. 

did somebody split through the code and figured out what the full api url is that the code is doing to get info? because whatever I try results in Request method not supported:

```
<ResponseResult>
<Success>false</Success>
<Code>1</Code>
<Msg> Request method not supported http://www.soliscloud.com:13333/v1/api/inverterDetail</Msg>
<Data/>
<CsrfToken/>
</ResponseResult>
```

**Comment by FGOD1983** [comment]
I finally found the issue!

Upon the migration the Plant ID is left empty. You need to edit the plant in order to let it generate an ID, and after that I was able to login. 

Thx HamsenBender for the solution: https://github.com/hultenvp/solis-sensor/issues/232#issuecomment-1566006420 :)

**Comment by steoj** [comment]
Edit the plant in order to let it generate an ID fixed the authentication issue for me too.

**Comment by Jonnehs** [comment]
Mine did have an ID, and the test worked, but editing the plant name also fixed this for me as well

Worth adding to the wiki @hultenvp ?
