### ISSUE TITLE
sensor.solis_energy_today reports same (incorrect) value for all three inverters

### ISSUE THREAD

**Issue by henrikeri** [hultenvp/solis-sensor#395]
**Describe the bug**
sensor.solis_energy_today, sensor.solis_energy_today_2 and sensor.solis_energy_today_3 reports the exact same value. It seems they all three might be added together

**Config**
Configured through the GUI with SolisCloud. Keys etc. nothing special selected.

**Versions**
Latest of all (non-beta)

**Debug Log*
Can't see anything meaningful

**Screenshots of inverter soliscloud vs reported in HA for same day (y-day)**
**Inverter 1:**
![image](https://github.com/user-attachments/assets/d66bc185-963c-46cb-8f44-3e2cf20cd12b)
![image](https://github.com/user-attachments/assets/542250bd-0a8b-45de-bb6d-fc3bdc9de00c)

**Inverter 2:**
![image](https://github.com/user-attachments/assets/ad8ae3a7-85dc-4427-8c56-338246780933)
![image](https://github.com/user-attachments/assets/9632da63-8aae-4b19-a372-8ccff42cfcc7)

**Inverter 3:**
![image](https://github.com/user-attachments/assets/28e726a2-cdf0-4294-8205-db8c0a5b442a)
![image](https://github.com/user-attachments/assets/30b184c0-7947-4f8f-befb-75b01e9a0b7b)

**Comment by hultenvp** [comment]
Can you check the energy_today value equals the energy of the whole plant/station?
https://soliscloud.com/#/station

There is a switch to use station instead of inverter for energy_today. Default it is off (i.e. inverter is used)
https://github.com/hultenvp/solis-sensor/blob/master/custom_components/solis/workarounds.yaml

There might be a bug in the workaround implementation, but let's start checking if it's set to false and if the value equals the plant value.

**Comment by henrikeri** [comment]
Hi,

It does indeed equal the energy of the whole station. I also double checked my "workarounds.yaml" and it is set to "false".

Cheers,
H

**Comment by hultenvp** [comment]
Thanks for confirming.

I'll have a shot at trying to reproduce.

**Comment by hultenvp** [comment]
@henrikeri : I think this should fix it, but I only have one inverter, so can't be 100% sure.
Please reopen if still an issue.
